# Site
repository: sproogen/resume-theme
favicon: images/favicon.png

# Personal info
name: Mauricio Blum
title: Frontend Developer
email: mauriciocblum@gmail.com
website: https://mauricioblum.github.io

# Social links
twitter_username: maublum
github_username: mauricioblum
# dribbble_username: jekyll
facebook_username: mauricioblum
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: mauricioblum
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Mauricio and I’m a passionate Frontend Developer and problem-solver.

  I love to develop meaningful interactions to the user and ensure best possible performance on all platforms.

  I also have a huge experience developing components for shared use in workspaces and multiple projects.

  I have 7+ years of Front End development experience and I'm a evangelist of Agile/Scrum principles and methodology and have extensive knowledge of project management software (JIRA, Trello, AzureDevOps).

  I am mainly focused in: <mark>React.js</mark>, <mark>React Native</mark>  and <mark>Node.js</mark>

  and other relevant skills include: <mark>Javascript</mark>,<mark>Typescript</mark>, <mark>Next.js</mark>, Jest, Enzyme, TDD, <mark>HTML5/CSS3</mark>, Redux, Redux Saga, Styled Components, Gatsby, Ruby on Rails, GraphQL, MySQL, Postgres, JSON/REST, Git/SVN.

  If you looking for a <mark>CV</mark> in a <mark>PDF</mark> format, you can download it here: [Download](./CV-MauricioBlum-2020-2.0.pdf)
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  - Fluent in English
  - Guitar player
  - Excellent Football(the real one) center-forward skills

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
