# Site
repository: sproogen/resume-theme
favicon: images/favicon.png

# Personal info
name: Mauricio Blum
title: Developer & Agilist
email: mauriciocblum@gmail.com
website: http://mauricioblum.github.io

# Social links
twitter_username: maublum
github_username: mauricioblum
# dribbble_username: jekyll
facebook_username: mauricioblum
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: mauricio-da-cunha-blum-31060846
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Mauricio and i'm a passionate Front-End Developer with extremely attention to detail. I love to develop meaningful interactions to the user and ensure best possible performance on all platforms.

  I am most skilled in: <mark>React.js</mark> and <mark>Node.js</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  - Fluent in English
  - Guitar player
  - Ebook designer

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
